"""Storage protocol and value objects."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from llmasm.graph.models import (
    Artifact,
    Checkpoint,
    Goal,
    MemoryItem,
    ModelCall,
    Run,
    RunNodeState,
    TaskEdge,
    TaskGraph,
    ToolCall,
    WorkspaceEdge,
    WorkspaceGraph,
)


@dataclass(frozen=True)
class FewShotExample:
    """Prior successful proposal for planner prompting."""

    proposal_json: str
    intent: str
    task_graph_id: str


@dataclass(frozen=True)
class ContextItem:
    """Rankable workspace context item."""

    id: str
    kind: str
    text: str
    score: float
    token_count: int
    item: object


class Storage(Protocol):
    """Storage contract used by compiler, runtime, and analysis."""

    def create_workspace_graph(self, graph: WorkspaceGraph) -> None: ...
    def load_workspace_graph(self, workspace_graph_id: str) -> WorkspaceGraph: ...
    def persist_task_graph(self, task_graph: TaskGraph) -> None: ...
    def load_task_graph(self, task_graph_id: str) -> TaskGraph: ...
    def create_run(self, run: Run) -> None: ...
    def load_run(self, run_id: str) -> Run: ...
    def update_run(self, run: Run) -> None: ...
    def create_run_node_state(self, state: RunNodeState) -> None: ...
    def list_run_node_states(self, run_id: str) -> list[RunNodeState]: ...
    def update_run_node_state(self, state: RunNodeState) -> None: ...
    def persist_task_edge(self, edge: TaskEdge) -> None: ...
    def list_task_edges(self, task_graph_id: str) -> list[TaskEdge]: ...
    def persist_workspace_edge(self, edge: WorkspaceEdge) -> None: ...
    def list_workspace_edges(self, workspace_graph_id: str) -> list[WorkspaceEdge]: ...
    def load_workspace_edges_for_task(self, task_graph_id: str) -> list[WorkspaceEdge]: ...
    def persist_artifact(self, artifact: Artifact) -> None: ...
    def update_artifact(self, artifact_id: str, superseded_by: str) -> None: ...
    def load_artifact(self, artifact_id: str) -> Artifact: ...
    def list_artifacts(self, run_id: str | None = None) -> list[Artifact]: ...
    def persist_goal(self, goal: Goal) -> None: ...
    def load_active_goal(self, workspace_graph_id: str) -> Goal | None: ...
    def load_goal(self, goal_id: str) -> Goal: ...
    def update_goal(self, goal: Goal) -> None: ...
    def persist_checkpoint(self, checkpoint: Checkpoint) -> None: ...
    def list_checkpoints(self, run_id: str) -> list[Checkpoint]: ...
    def persist_tool_call(self, call: ToolCall) -> None: ...
    def list_tool_calls(self, run_id: str) -> list[ToolCall]: ...
    def persist_model_call(self, call: ModelCall) -> None: ...
    def list_model_calls(self, run_id: str) -> list[ModelCall]: ...
    def persist_memory_item(self, item: MemoryItem) -> None: ...
    def list_memory_items(self, workspace_graph_id: str) -> list[MemoryItem]: ...
    def retrieve_few_shot_examples(
        self, workspace_graph_id: str, intent: str, limit: int
    ) -> list[FewShotExample]: ...
    def find_cached_artifact(
        self, node_execution_key: str, input_artifact_ids: list[str]
    ) -> Artifact | None: ...
    def persist_compilation_failure(self, workspace_graph_id: str, payload: dict[str, object]) -> None: ...
    def search_memory(
        self,
        workspace_graph_id: str,
        query: str,
        filters: dict[str, Any] | None = None,
        limit: int = 20,
        kinds: set[str] | None = None,
    ) -> list[MemoryItem]: ...
    def retrieve_workspace_context(
        self,
        workspace_graph_id: str | list[str],
        query: str,
        budget_tokens: int,
        filters: dict[str, Any] | None = None,
        kinds: set[str] | None = None,
    ) -> list[ContextItem]: ...
